### ISSUE TITLE
operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by dincerkurnaz** [GokulDas027/Chrome-dino-auto-run#1]
File "/Users/dincersalihkurnaz/Desktop/Object-Oriented-Programming/OOP Codes/choromdino.py", line 39, in <module>
    frame_diff = np.subtract(ref_frame,frame).sum()

ValueError: operands could not be broadcast together with shapes (35,95,3) (35,95,4)

**Comment by GokulDas027** [comment]
It's due to the difference in shape of the captured frame and reference frame.
Here one of the frame is of RGB and other may be in RGBA or something.
The fix is to have both frames in same shape. Color doesn't matters here.
A quick patch can be
`
frame_diff = np.subtract(ref_frame[:][:][:3] , frame[:][:][:3]).sum()
`
And hereby converting both to RGB.

**Comment by GokulDas027** [comment]
Converting both to Greyscale too should work, haven't tried it though.
That would be computationally efficient too.
